### ISSUE TITLE
Can i know that your editor plugin list with atom?

### ISSUE THREAD

**Issue by duncup** [steelbrain/ama#10]
I'd like to know that,what plugin format your code in your editor?
I mind nodejs code.
If this can i like know your plugin list.
I'm re config my atom editor now.

Thanks for your time.
duncup

**Comment by steelbrain** [comment]
Hi @duncup!

The list of Atom packages that I use for writing Node.js packages is as follows:

- linter
- linter-eslint
- declarations
- flow-ide
- intentions
- language-babel
- merge-conflicts

Thank You!
