### ISSUE TITLE
What's your favorite place on earth and why?

### ISSUE THREAD

**Issue by sindresorhus** [steelbrain/ama#5]

**Comment by steelbrain** [comment]
My favorite place on Earth is the [Saif Ul Malook Valley](https://www.google.com/search?q=Saif+ul+Malook+valley&tbm=isch). I love it because of the fact that it's one of the most beautiful place on Earth IMHO.

**Comment by sindresorhus** [comment]
That looks stunning!

**Comment by steelbrain** [comment]
I know right :wink:

**Comment by sindresorhus** [comment]
Where I used to live: https://instagram.com/p/eCgnLUoUO9/ https://instagram.com/p/S0ypITIUIE/ https://instagram.com/p/SRZp51oUDy/

**Comment by steelbrain** [comment]
That is so beautiful :cry:
