### ISSUE TITLE
What have you learned from running the Atom Linter project?

### ISSUE THREAD

**Issue by sindresorhus** [steelbrain/ama#6]

**Comment by steelbrain** [comment]
I have learned that not every programmer in the world is a nice guy, there are people who will stop you even when you do the right thing and nobody will rise against them. I also learned that sense of safety and trust is the most important thing while working with Open Source Organizations run by the people you barely know. I have also learned that if you trust the right people your repo, they will work real hard on it.

Here's my Atom Linter story, I wrote a base linter from the ground up, I was invited to the org and the then admin said that they would work hard on it. I had never seen mean people on GitHub so I agreed. Later on, they removed me from the org and my own repo for working on it. Then there were a lot of political clashes and the single admin (aka dictator) had to step down and several other people (including me) are now in position and the Organization is more active than it ever was. The repo as well as the previous `linter` (that existed before my rewrite) was almost dead, bugs hadn't been solved for months and package authors were moving away, but with my rewrite and constant improvements, new linters are added each week and the projects that had previously reinvented the wheel are now using the API.
